### PR TITLE
Show that we need PageRank

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Related to https://github.com/erikbern/eigenstuff/pull/2
Simple removal of all edges from Go to * makes:
| 22.76% |                 java |
| 15.73% |                   go |
| 14.31% |                    c |
| 13.46% |                  c++ |
|  6.83% |                   c# |
|  6.12% |               python |
|  5.70% |                scala |
|  3.98% |                 rust |
|  2.93% |                  php |
|  2.02% |          objective c |
|  1.54% |                 ruby |
|  1.07% |                swift |
|  1.00% |                 node |
|  0.65% |               kotlin |
|  0.40% |                    r |
|  0.30% |               matlab |
|  0.28% |              haskell |
|  0.24% |               pascal |
|  0.21% |                cobol |
|  0.13% |               erlang |
|  0.11% |              fortran |
|  0.10% |         visual basic |
|  0.07% |                  lua |
|  0.05% |              clojure |
|  0.02% |                 perl |
|  0.01% |                 lisp |

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Surprise-surprise!

**Comment by erikbern** [comment]
i'm not following. how does this prove that we need pagerank?

**Comment by vmarkovtsev** [comment]
Results from PageRank:
```
| 19.22% |                 java |
| 13.49% |                   go |
| 13.16% |                    c |
| 11.33% |                  c++ |
|  7.00% |               python |
|  6.33% |                   c# |
|  4.95% |                scala |
|  3.52% |                 rust |
|  2.96% |                  php |
|  2.76% |          objective c |
|  2.02% |                 ruby |
|  1.76% |                swift |
|  1.49% |                 node |
|  1.04% |               kotlin |
|  0.99% |                    r |
|  0.93% |              haskell |
|  0.90% |               matlab |
|  0.80% |               erlang |
|  0.77% |               pascal |
|  0.74% |                cobol |
|  0.69% |              fortran |
|  0.66% |              clojure |
|  0.66% |         visual basic |
|  0.65% |                  lua |
|  0.61% |                 perl |
|  0.59% |                 lisp |
```

I can conclude that PageRank does not help in this case. I am disappointed - this seems to be very unstable. How can Java be the dominant if the only thing I did was restricting the transition from Go to *

**Comment by ellisonbg** [comment]
I think the big issue is how the diagonal element are handled. Making minor changes to the off-diagonal element doesn't fix that.

**Pull request closed without merging**
